@URL = http://localhost:5000

############################################
### CUSTOMERS
### Login as a customer ----DONE---
POST {{URL}}/customer/signin HTTP/1.1
content-type: application/json

{
    "email": "adminemail",
    "password": "admin"
}

### Signup as a customer ---DONE---
POST {{URL}}/customer/new HTTP/1.1
content-type: application/json

{
    "firstName": "Admin",
    "lastName": "Admin",
    "phone": "07039439340",
    "email": "admine",
    "address": "1, Pike Road North, Dagenham, UK",
    "password": "admin",
    "date": "12/22/2020"
}

### Get all customers ---DONE---
GET {{URL}}/customer

### Find a customers ---DONE---
# POST {{URL}}/customer/:id
GET {{URL}}/customer/5ed3d609ef4f6e3be45d5898

### Update a customers ---DONE---
# PUT {{URL}}/customer/:id
PUT {{URL}}/customer/5ed3c95dae15df159864bf6e HTTP/1.1
content-type: application/json

{
    "firstName": "Admin test edited",
    "lastName": "Admin last edited",
    "phone": "07039439340",
    "email": "edited",
    "address": "1, Pike Road North, Dagenham, UK",
    "password": "edited",
    "date": "12/22/2020"
}

### Delete a customers ---DONE---
# DELETE {{URL}}/customer/delete/:id
DELETE {{URL}}/customer/5ed3d609ef4f6e3be45d5898


##############################################
##############################################
##############################################
### PRODUCTS
### Get all product
GET {{URL}}/product

### Get front page product
GET {{URL}}/product/home


### New a product ---DONE---
POST {{URL}}/product/new HTTP/1.1
content-type: application/json

{
    "name": "Hair Glue",
    "category": "Glue",
    "color": "blond",
    "price": 200,
    "length": 15,
    "frontPage": true,

}

### Get a product ---DONE---
# GET {{URL}}/product/:id
GET {{URL}}/product/5ed3f98574f4dd3e2039723f



### Update a product ---DONE---
PUT {{URL}}/product/5ed3f98574f4dd3e2039723f HTTP/1.1
content-type: application/json

{
    "name": "Curly Large Hair",
    "category": "Curly Hair",
    "color": "black",
    "price": 20,
    "length": 15
}

### Delete a product ---DONE---
DELETE {{URL}}/product/5ed3f98574f4dd3e2039723f

###################################################
###################################################
###################################################
###################################################
###################################################
### CART
### Get all cart --DONE--
GET {{URL}}/cart

### New Cart --DONE--
POST {{URL}}/cart

### Delete a cart --DONE--
DELETE {{URL}}/cart/:id

###################################################
###################################################
###################################################
###################################################
###################################################
### Admin Signin
POST {{URL}}/admin/login/ HTTP/1.1
content-type: application/json

{
    "email": "Admin test edited",
    "password": "Admin last edited"
}